export default {
    HOME_BANNER:'HOME_BANNER',
    HOME_ARTICLE:'HOME_ARTICLE',
    HOME_PAGENUM:'HOME_PAGENUM',
    HOME_PAGECOUNT:'HOME_PAGECOUNT',
    HOME_TOPARTICLE: 'HOME_TOPARTICLE',
    SQUARE_ARTICLE:'SQUARE_ARTICLE',
    SQUARE_PAGENUM:'SQUARE_PAGENUM',
    SQUARE_PAGECOUNT:'SQUARE_PAGECOUNT',
    USERINFO: 'USERINFO',
    SCORE: 'SCORE',
    THEME_TYPE:'THEME_TYPE',
}