export default {
    HOME_BANNER:'HOME_BANNER',
    HOME_ARTICLE:'HOME_ARTICLE',
    HOME_PAGENUM:'HOME_PAGENUM',
    HOME_PAGECOUNT:'HOME_PAGECOUNT',
    HOME_TOPARTICLE: 'HOME_TOPARTICLE',
    THEME_TYPE:'THEME_TYPE',
}